### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ritwik12**
A brief intro about Flix on README.md

### CODE REVIEW

**Comment by magnus-madsen** [comment]
I think perhaps it would be better to refer to the main Flix repository or the website. Let me think about it.

**Comment by ritwik12** [comment]
@magnus-madsen I think description is needed for the one's who are visiting flix for the very first time.
But take your time and think.

**Comment by ritwik12** [comment]
@magnus-madsen   Any conclusion?

**Comment by magnus-madsen** [comment]
Hey. I don't think we want to maintain the same text in two different places. I guess we could add a link to the website though.

**Comment by ritwik12** [comment]
@magnus-madsen  Alright as you say, let me add link.

**Comment by ritwik12** [comment]
You want "flix.github.io" to be the link or should write "The Flix Programming Language" and make that a link?

**Comment by magnus-madsen** [comment]
I guess "The Flix Programming Language" as a link would be good.

**Comment by ritwik12** [comment]
@magnus-madsen Good to go :)

**Comment by ritwik12** [comment]
resolved #5

**Comment by ritwik12** [comment]
On 10-Aug-2017 1:09 am, "Magnus Madsen" <notifications@github.com> wrote:

I think perhaps it would be better to refer to the main Flix repository or
the website. Let me think about it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/flix/flix.github.io/pull/6#issuecomment-321359952>, or mute
the thread

**Pull request merged**
